FROM nginx:latest

# Roda um echo e coloca sua saída na pasta aonde o nginx vai ler
# Ao final, será criada uma nova camada na minha imagem
RUN echo '<h1>Hello World</h1>' > /usr/share/nginx/html/index.html